/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjahit;

/**
 *
 * @author Toshiba
 */
public class form_menuUtama extends javax.swing.JFrame {

    /**
     * Creates new form form_menuUtama
     */
    public form_menuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMaster = new javax.swing.JMenu();
        jplgitem = new javax.swing.JMenuItem();
        jpenjahititem = new javax.swing.JMenuItem();
        jtransaksi = new javax.swing.JMenu();
        jtransaksiitem = new javax.swing.JMenuItem();
        jbayaritem = new javax.swing.JMenuItem();
        jlogout = new javax.swing.JMenu();
        jlogoutitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form_MenuUtama");

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Jl. Kenanga No. 18 Gemantar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Sistem Informasi Jasa Jahit eRro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jMaster.setText("Master");

        jplgitem.setText("Pelanggan");
        jplgitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jplgitemActionPerformed(evt);
            }
        });
        jMaster.add(jplgitem);

        jpenjahititem.setText("Penjahit");
        jpenjahititem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpenjahititemActionPerformed(evt);
            }
        });
        jMaster.add(jpenjahititem);

        jMenuBar2.add(jMaster);

        jtransaksi.setText("Transaksi");

        jtransaksiitem.setText("Transaksi");
        jtransaksiitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtransaksiitemActionPerformed(evt);
            }
        });
        jtransaksi.add(jtransaksiitem);

        jbayaritem.setText("Pembayaran");
        jbayaritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbayaritemActionPerformed(evt);
            }
        });
        jtransaksi.add(jbayaritem);

        jMenuBar2.add(jtransaksi);

        jlogout.setText("LogOut");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });

        jlogoutitem.setText("LogOut");
        jlogoutitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutitemActionPerformed(evt);
            }
        });
        jlogout.add(jlogoutitem);

        jMenuBar2.add(jlogout);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jplgitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jplgitemActionPerformed
        // TODO add your handling code here:
        new form_pelanggan().setVisible(true);
    }//GEN-LAST:event_jplgitemActionPerformed

    private void jpenjahititemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpenjahititemActionPerformed
        // TODO add your handling code here:
        new form_penjahit().setVisible(true);
    }//GEN-LAST:event_jpenjahititemActionPerformed

    private void jtransaksiitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtransaksiitemActionPerformed
        // TODO add your handling code here:
        new form_transaksi().setVisible(true);
    }//GEN-LAST:event_jtransaksiitemActionPerformed

    private void jbayaritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbayaritemActionPerformed
        // TODO add your handling code here:
        new form_pembayaran().setVisible(true);
    }//GEN-LAST:event_jbayaritemActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jlogoutitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutitemActionPerformed
        // TODO add your handling code here:
        new form_login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlogoutitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMaster;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jbayaritem;
    private javax.swing.JMenu jlogout;
    private javax.swing.JMenuItem jlogoutitem;
    private javax.swing.JMenuItem jpenjahititem;
    private javax.swing.JMenuItem jplgitem;
    private javax.swing.JMenu jtransaksi;
    private javax.swing.JMenuItem jtransaksiitem;
    // End of variables declaration//GEN-END:variables
}
